global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Runtime.InteropServices;
global using System.Threading;
global using System.Windows;
global using System.Windows.Controls;
global using Community.VisualStudio.Toolkit;
global using Microsoft.VisualStudio;
global using Microsoft.VisualStudio.PlatformUI;
global using Microsoft.VisualStudio.Shell;
global using Microsoft.VisualStudio.Shell.Interop;
global using Microsoft.VisualStudio.TextManager.Interop;
global using Task = System.Threading.Tasks.Task;
global using DTEWindow = EnvDTE.Window;
