// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloseTabs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CloseTabsString = "7275d502-42d9-4da4-be67-7cb657a9083f";
        public static Guid CloseTabs = new Guid(CloseTabsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CloseTabsMenuGroup = 0x0001;
        public const int CloseAllTabsToTheLeft = 0x0100;
        public const int CloseAllTabsToTheRight = 0x0101;
    }
}